FROM python:3.10-slim

WORKDIR /app
COPY . .

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y python3-pip wget && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    pip install -r requirements.txt && \
    python setup.py install

